version: '3.8'

services:
  postgres:
    image: 'postgres:latest'
    container_name: postgres-container
    restart: always
    environment:
      - 'POSTGRES_DB=motorhub'
      - 'POSTGRES_PASSWORD=angel'
      - 'POSTGRES_USER=angel'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
